"""AI Router テスト

TEST_PLAN.md で定義されたテストケース:
- RTR-01: test_get_default_provider - デフォルト設定で取得
- RTR-02: test_workspace_override - Workspace別上書き
- RTR-03: test_room_override - Room別上書き
- RTR-04: test_provider_not_configured - 未設定プロバイダーでエラー
- RTR-05: test_fallback_on_error - エラー時フォールバック
"""

from typing import Any

import pytest

from src.ai.base import AIProvider, AIProviderError, AIProviderNotConfiguredError
from src.ai.router import AIRouter


class MockProvider(AIProvider):
    """テスト用のモックプロバイダー"""

    def __init__(self, name: str = "mock", model: str = "mock-model") -> None:
        self._name = name
        self._model = model

    @property
    def name(self) -> str:
        return self._name

    @property
    def model(self) -> str:
        return self._model

    async def generate(self, prompt: str, **kwargs: Any) -> str:
        return f"Generated by {self._name}/{self._model}"

    async def embed(self, text: str) -> list[float]:
        return [0.1] * 1536


class FailingProvider(AIProvider):
    """常に失敗するプロバイダー（フォールバックテスト用）"""

    def __init__(self, name: str = "failing", model: str = "failing-model") -> None:
        self._name = name
        self._model = model

    @property
    def name(self) -> str:
        return self._name

    @property
    def model(self) -> str:
        return self._model

    async def generate(self, prompt: str, **kwargs: Any) -> str:
        raise AIProviderError("Provider failed")

    async def embed(self, text: str) -> list[float]:
        raise AIProviderError("Provider failed")


@pytest.fixture
def sample_config() -> dict[str, Any]:
    """テスト用の設定"""
    return {
        "ai_providers": {
            "openai": {
                "api_key": "test-key",
                "models": ["gpt-4o", "gpt-4o-mini", "text-embedding-3-small"],
            },
            "anthropic": {
                "api_key": "test-key",
                "models": ["claude-3-5-sonnet-20241022"],
            },
            "google": {
                "api_key": "test-key",
                "models": ["gemini-1.5-flash"],
            },
        },
        "ai_routing": {
            "summary": {"provider": "openai", "model": "gpt-4o-mini"},
            "rag_answer": {"provider": "anthropic", "model": "claude-3-5-sonnet-20241022"},
            "search_embedding": {"provider": "openai", "model": "text-embedding-3-small"},
        },
        "workspace_overrides": {
            "workspace_a": {
                "summary": {"provider": "google", "model": "gemini-1.5-flash"},
            },
        },
        "room_overrides": {
            "room_123": {
                "summary": {"provider": "anthropic", "model": "claude-3-5-sonnet-20241022"},
            },
        },
        "ai_fallback": {
            "summary": [
                {"provider": "openai", "model": "gpt-4o-mini"},
                {"provider": "google", "model": "gemini-1.5-flash"},
            ],
        },
    }


@pytest.fixture
def router(sample_config: dict[str, Any]) -> AIRouter:
    """AIRouterインスタンス"""
    return AIRouter(sample_config)


class TestAIRouter:
    """AIRouterのテスト"""

    # RTR-01: デフォルト設定で取得
    def test_get_default_provider(self, router: AIRouter) -> None:
        """デフォルト設定でプロバイダー情報を取得できる"""
        provider_info = router.get_provider_info("summary")

        assert provider_info["provider"] == "openai"
        assert provider_info["model"] == "gpt-4o-mini"

    def test_get_default_provider_rag(self, router: AIRouter) -> None:
        """RAG回答のデフォルト設定を取得できる"""
        provider_info = router.get_provider_info("rag_answer")

        assert provider_info["provider"] == "anthropic"
        assert provider_info["model"] == "claude-3-5-sonnet-20241022"

    # RTR-02: Workspace別上書き
    def test_workspace_override(self, router: AIRouter) -> None:
        """Workspace設定でプロバイダーが上書きされる"""
        provider_info = router.get_provider_info("summary", workspace_id="workspace_a")

        assert provider_info["provider"] == "google"
        assert provider_info["model"] == "gemini-1.5-flash"

    def test_workspace_override_not_configured(self, router: AIRouter) -> None:
        """上書き設定がないWorkspaceはデフォルト設定を使う"""
        provider_info = router.get_provider_info("summary", workspace_id="workspace_b")

        assert provider_info["provider"] == "openai"
        assert provider_info["model"] == "gpt-4o-mini"

    # RTR-03: Room別上書き
    def test_room_override(self, router: AIRouter) -> None:
        """Room設定でプロバイダーが上書きされる"""
        provider_info = router.get_provider_info("summary", room_id="room_123")

        assert provider_info["provider"] == "anthropic"
        assert provider_info["model"] == "claude-3-5-sonnet-20241022"

    def test_room_override_priority(self, router: AIRouter) -> None:
        """Room設定はWorkspace設定より優先される"""
        # workspace_aはsummaryをgoogleに設定しているが
        # room_123はanthropicに設定 → room_123の設定が優先
        provider_info = router.get_provider_info(
            "summary", workspace_id="workspace_a", room_id="room_123"
        )

        assert provider_info["provider"] == "anthropic"
        assert provider_info["model"] == "claude-3-5-sonnet-20241022"

    def test_room_override_not_configured(self, router: AIRouter) -> None:
        """上書き設定がないRoomはWorkspaceまたはデフォルト設定を使う"""
        provider_info = router.get_provider_info(
            "summary", workspace_id="workspace_a", room_id="room_456"
        )

        # room_456には設定がないのでworkspace_aの設定を使う
        assert provider_info["provider"] == "google"
        assert provider_info["model"] == "gemini-1.5-flash"

    # RTR-04: 未設定プロバイダーでエラー
    def test_provider_not_configured(self, router: AIRouter) -> None:
        """設定されていないpurposeでエラー"""
        with pytest.raises(AIProviderNotConfiguredError) as exc_info:
            router.get_provider_info("unknown_purpose")

        assert "unknown_purpose" in str(exc_info.value)

    def test_provider_not_in_providers(self, sample_config: dict[str, Any]) -> None:
        """ai_providersに存在しないプロバイダーを参照した場合エラー"""
        # groqを参照しているがai_providersにgroqがない
        sample_config["ai_routing"]["notification"] = {
            "provider": "groq",
            "model": "llama-3.1-70b",
        }
        router = AIRouter(sample_config)

        with pytest.raises(AIProviderNotConfiguredError) as exc_info:
            router.get_provider_info("notification")

        assert "groq" in str(exc_info.value)

    # RTR-05: エラー時フォールバック
    def test_get_fallback_providers(self, router: AIRouter) -> None:
        """フォールバックプロバイダー情報のリストを取得できる"""
        fallbacks = router.get_fallback_info("summary")

        assert len(fallbacks) == 2
        assert fallbacks[0]["provider"] == "openai"
        assert fallbacks[0]["model"] == "gpt-4o-mini"
        assert fallbacks[1]["provider"] == "google"
        assert fallbacks[1]["model"] == "gemini-1.5-flash"

    def test_get_fallback_empty_if_not_configured(self, router: AIRouter) -> None:
        """フォールバック未設定の場合は空リストを返す"""
        fallbacks = router.get_fallback_info("rag_answer")

        assert fallbacks == []


class TestAIRouterValidation:
    """AIRouter バリデーションのテスト"""

    def test_empty_config(self) -> None:
        """空の設定でRouterを作成するとエラー"""
        with pytest.raises(ValueError) as exc_info:
            AIRouter({})

        assert "ai_routing" in str(exc_info.value).lower()

    def test_missing_ai_providers(self) -> None:
        """ai_providersがない場合エラー"""
        config = {
            "ai_routing": {
                "summary": {"provider": "openai", "model": "gpt-4o-mini"},
            },
        }
        with pytest.raises(ValueError) as exc_info:
            AIRouter(config)

        assert "ai_providers" in str(exc_info.value).lower()


class TestAIProviderBase:
    """AIProvider基底クラスのテスト"""

    def test_mock_provider_generate(self) -> None:
        """MockProviderがgenerateを実装している"""
        provider = MockProvider("test", "test-model")

        import asyncio

        result = asyncio.get_event_loop().run_until_complete(provider.generate("test prompt"))

        assert "test/test-model" in result

    def test_mock_provider_embed(self) -> None:
        """MockProviderがembedを実装している"""
        provider = MockProvider("test", "test-model")

        import asyncio

        result = asyncio.get_event_loop().run_until_complete(provider.embed("test text"))

        assert len(result) == 1536
        assert all(isinstance(v, float) for v in result)

    def test_provider_properties(self) -> None:
        """プロバイダーのプロパティを取得できる"""
        provider = MockProvider("openai", "gpt-4o")

        assert provider.name == "openai"
        assert provider.model == "gpt-4o"


class TestConfigLoading:
    """設定読み込みのテスト"""

    def test_router_from_yaml_file(self, tmp_path: Any) -> None:
        """YAMLファイルからRouterを作成できる"""
        yaml_content = """
ai_providers:
  openai:
    api_key: test-key
    models:
      - gpt-4o-mini

ai_routing:
  summary:
    provider: openai
    model: gpt-4o-mini
"""
        config_file = tmp_path / "config.yaml"
        config_file.write_text(yaml_content)

        router = AIRouter.from_yaml(str(config_file))
        provider_info = router.get_provider_info("summary")

        assert provider_info["provider"] == "openai"
        assert provider_info["model"] == "gpt-4o-mini"

    def test_router_from_yaml_with_env_vars(self, tmp_path: Any, monkeypatch: Any) -> None:
        """環境変数を展開してRouterを作成できる"""
        monkeypatch.setenv("TEST_API_KEY", "my-secret-key")

        yaml_content = """
ai_providers:
  openai:
    api_key: ${TEST_API_KEY}
    models:
      - gpt-4o-mini

ai_routing:
  summary:
    provider: openai
    model: gpt-4o-mini
"""
        config_file = tmp_path / "config.yaml"
        config_file.write_text(yaml_content)

        router = AIRouter.from_yaml(str(config_file))

        # 内部で環境変数が展開されていることを確認
        assert router._config["ai_providers"]["openai"]["api_key"] == "my-secret-key"
